name: sits_dl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - geopandas
  - rich
  - tqdm
  - pyarrow
  - pip
  - pyyaml
  - pip:
    - mmap-ninja
    - earthengine-api 
    - hydra-core